library(R.utils)
library(tidyverse)
library(tidybulk)
library(ggplot2)
library(plotly)
library(stringr)
library(future)
library(furrr)
library(cluster)
library(factoextra)

load("/stornext/Home/data/allstaff/w/wu.j/Master Project/cellsig/dev/counts.rda")

tt_simple <- readRDS("dev/intermediate_data/tt_simple.rds")

# Functions ======================================================

## 2.5 Silhouette function
sil_func0 <- function(.markers, .method){
  .markers %>% 
    nest(rdim = - level_0) %>% 
    mutate(rdim = map(rdim, ~ .x %>% 
                        distinct(sample, symbol, count_scaled, cell_type))) %>% 
    mutate(rdim = map(rdim, ~ .x %>%
                        reduce_dimensions(sample, symbol, count_scaled,
                                          method = .method,
                                          action = "add",
                                          transform = log1p,
                                          # check_duplicates is for Rtsne method
                                          check_duplicates = FALSE) %>% 
                        
                        # save symbols for calculating real_size while reducing replicated rows resulted from symbol
                        nest(data_symbol = c(symbol, count_scaled))
    )) %>%
    
    # calculate the dissimilarity matrix with PC values
    mutate(distance = map(rdim, ~ .x %>%
                            select(contains(str_sub(.method, end = -2L))) %>%
                            factoextra::get_dist(method = "euclidean")
    )) %>%
    
    # calculate silhouette score
    mutate(sil = map2(rdim, distance, 
                      ~ silhouette(as.numeric(as.factor(`$`(.x, cell_type))), .y)
    )) %>% 
    mutate(sil = map(sil, ~ .x %>% summary())) %>%
    mutate(sil = map(sil, ~ .x %>% `$`(avg.width) ))%>% 
    mutate(sil = unlist(sil)) %>% 
    
    # obtain the actual number of signature genes
    mutate(real_size = map_int(rdim, ~ .x$data_symbol %>% 
                                 map_int(~ n_distinct(.x$symbol)) %>% 
                                 unlist() %>% 
                                 unique() ))
  
}

# No hierarchy CIBERSORTx files creation=============================

## create reference file

reference <- tt_simple %>% 
  unnest(data) %>% 
  select(sample, cell_type, count, symbol) %>% 
  mutate(sample = str_replace_all(sample, "\\.", "_")) %>%
  pivot_wider(names_from = c(cell_type, sample), values_from = count, names_sep=".")

## vector ref_names is produced below yet used here to create header for reference file
ref_names <- tt_simple %>% 
  unnest(data) %>% 
  mutate(sample = str_replace_all(sample, "\\.", "_")) %>%
  unite(cell_sample, c(cell_type, sample), sep = ".") %>% 
  pull(cell_sample) %>% 
  unique()

header <- ref_names %>% 
  str_extract(".*(?=\\.)") %>% 
  insert(ats=1, "symbol")

names(reference) <- header

reference

## create phenoclass file
cell_types <- tt_simple %>%
  unnest(data) %>% 
  pull(cell_type) %>% 
  unique()

ref_tibble <- tibble(ref_names, value=1:length(ref_names)) %>% 
  pivot_wider(names_from = ref_names, values_from = value)

phenoclass <- tibble(cell_types) %>% 
  bind_cols(ref_tibble) %>% 
  pivot_longer(-cell_types, names_to="ref_names", values_to="membership") %>% 
  mutate(membership = if_else(str_detect(ref_names, cell_types), 1, 2)) %>% 
  pivot_wider(names_from = ref_names, values_from = membership)


# save files as txt files (tab separated files)
write_tsv(reference, "reference.txt")

write_tsv(phenoclass, "phenoclass.txt", col_names = FALSE)

# Analysis on the signature matrix generated by CIBERSORTx========================
CIBERSORTx_Job20_signature_bm_K999 <- 
  read_delim("dev/cibersortx_NH/CIBERSORTx_Job20_signature.bm.K999.txt", 
             "\t", escape_double = FALSE, trim_ws = TRUE)

ciber_sig <- CIBERSORTx_Job20_signature_bm_K999 %>% 
  pull(NAME)

ciber_sil <- tt_simple %>% 
  mutate(data = map(data, ~ .x %>% filter(symbol %in% ciber_sig))) %>% 
  unnest(data) %>% 
  sil_func0("PCA")

ciber_sil

ciber_pca <- ciber_sil %>% 
  pluck("rdim", 1) %>% 
  ggplot(aes(x = PC1, y = PC2, colour = cell_type, label = sample)) +
  geom_point() +
  # stat_ellipse(type = 't') +
  theme_bw(
    title = "ciber_pca",
    plot.title = element_text(hjust=0.5) )

ciber_pca

ggsave("ciber_pca.png", ciber_pca)

